# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be22ab09b4eb8b5f0055549e1695385aab1b45e604866b540488a4cb9e1b4493941b6f14fdbec3a53d1c6c4c7e3a899ecf2fb10dc492fca9fb5ce87723b751e6

test:
  secret_key_base: 6945d9c4cbcf625bbeb149820bf8816a16ee7549d18eb0fe87552d7a37293a8cc11b444017fd03020c606dc549719d7416b07ba92d2e47fab659ca52d387c3a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
